import { ColorTheme, ColorThemeId } from '../types/settings';

export const THEMES: Record<ColorThemeId, ColorTheme> = {
  'classic-red': {
    id: 'classic-red',
    name: 'Classic Red',
    primary: '#DC0A2D',
    primaryDark: '#89061C',
    accent: '#28AAFD',
    accentLight: '#5BC0FF',
    screen: '#232323',
    screenText: '#E8E8E8',
    screenTextSecondary: '#A8B5C0',
    cyan: '#3DE8FF',
    yellow: '#FFCB05',
    uiSurface: '#DEDEDE',
  },
  'ocean-blue': {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    primary: '#1565C0',
    primaryDark: '#0D47A1',
    accent: '#00E5FF',
    accentLight: '#6EFFFF',
    screen: '#1A1E2E',
    screenText: '#E0E8F0',
    screenTextSecondary: '#8899AA',
    cyan: '#00E5FF',
    yellow: '#FFD740',
    uiSurface: '#CFD8DC',
  },
  'forest-green': {
    id: 'forest-green',
    name: 'Forest Green',
    primary: '#2E7D32',
    primaryDark: '#1B5E20',
    accent: '#69F0AE',
    accentLight: '#A5FFD6',
    screen: '#1A231A',
    screenText: '#D8ECD8',
    screenTextSecondary: '#88A888',
    cyan: '#69F0AE',
    yellow: '#FFE082',
    uiSurface: '#C8E6C9',
  },
  'midnight-dark': {
    id: 'midnight-dark',
    name: 'Midnight Dark',
    primary: '#263238',
    primaryDark: '#1A2327',
    accent: '#80DEEA',
    accentLight: '#B2EBF2',
    screen: '#0D1117',
    screenText: '#C9D1D9',
    screenTextSecondary: '#8B949E',
    cyan: '#80DEEA',
    yellow: '#FFC107',
    uiSurface: '#37474F',
  },
  'solar-gold': {
    id: 'solar-gold',
    name: 'Solar Gold',
    primary: '#E65100',
    primaryDark: '#BF360C',
    accent: '#FFAB00',
    accentLight: '#FFD740',
    screen: '#2A1F0E',
    screenText: '#F0E4D0',
    screenTextSecondary: '#B89A6A',
    cyan: '#FFAB00',
    yellow: '#FFF176',
    uiSurface: '#FFE0B2',
  },
  'cyber-purple': {
    id: 'cyber-purple',
    name: 'Cyber Purple',
    primary: '#6A1B9A',
    primaryDark: '#4A148C',
    accent: '#E040FB',
    accentLight: '#EA80FC',
    screen: '#1A0E2E',
    screenText: '#E8D8F8',
    screenTextSecondary: '#9E88B8',
    cyan: '#E040FB',
    yellow: '#FFD54F',
    uiSurface: '#CE93D8',
  },
};

export const DEFAULT_THEME_ID: ColorThemeId = 'classic-red';
